### ISSUE TITLE
数据库没有返回数据报错

### ISSUE THREAD

**Issue by denzhengwei** [wangxinfei0118/baldbear-node-api#1]
运行环境ubuntu22/node18/mysql8.0/

后端报错如下：
0|baldbear | TypeError: Cannot read properties of undefined (reading '0')
0|baldbear |     at Query._callback (/home/ubuntu/blog/back/services/noteService.js:43:22)
0|baldbear |     at Sequence.end (/home/ubuntu/blog/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
0|baldbear |     at /home/ubuntu/blog/back/node_modules/mysql/lib/Pool.js:205:13
0|baldbear |     at Handshake.onConnect (/home/ubuntu/blog/back/node_modules/mysql/lib/Pool.js:58:9)
0|baldbear |     at Handshake.<anonymous> (/home/ubuntu/blog/back/node_modules/mysql/lib/Connection.js:526:10)
0|baldbear |     at Handshake._callback (/home/ubuntu/blog/back/node_modules/mysql/lib/Connection.js:488:16)
0|baldbear |     at Sequence.end (/home/ubuntu/blog/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
0|baldbear |     at Handshake.ErrorPacket (/home/ubuntu/blog/back/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
0|baldbear |     at Protocol._parsePacket (/home/ubuntu/blog/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
0|baldbear |     at Parser._parsePacket (/home/ubuntu/blog/back/node_modules/mysql/lib/protocol/Parser.js:433:10)

查询笔记总数返回结果为undefined

exports.getNoteList = async (queryObj) => {
  // 开始查询的index
  const start = (queryObj.current - 1) * queryObj.size
  // 查询笔记总数
  const sql_note_count = `select count(*) total from bb_notes ` + (queryObj.label ? `where label='${queryObj.label}'` : '')
  // 根据queryObj.label是否存在 判断是否是根据标签查询
  const sql_note_list =
    `select note_id, title, summary, label, image_url, view_count, chat_count, create_date, update_date from bb_notes ` +
    (queryObj.label ? `where label='${queryObj.label}'` : '') +
    ` order by create_date desc limit ${start},${queryObj.size}`
  const noteCount = new Promise((resolve, reject) => {
    db.query(sql_note_count, (err, results) => {
      if (err) {
        reject(err)
      }
        console.log('结果',results)
      resolve(results[0])
    })
  })

**Comment by wangxinfei0118** [comment]
我认为应该和mysql版本有关系，项目代码所用的mysql版本为5.7，请尝试修改sql语句是否可以从数据库取到数据

**Comment by denzhengwei** [comment]
好的感谢，目前已经装了其他blog
